import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import AlbumCard from '../../src/Components/cards/AlbumCard'
import CollectionLayout from '../../src/Components/layouts/CollectionLayout'
import LoadingAnimation from '../../src/Components/Loading'
import { useAppContext } from '../../src/Config/Context'
import { ContextInterface } from '../../types/types'
import UserAlbumCard from './../../src/Components/cards/UserAlbumCard';

const Albums = () => {
  
  const router = useRouter();
  const { userAlbums, code } = useAppContext() as ContextInterface;
  React.useEffect(()=>{
    if(!code) router.replace('/');
  }, [code, router])

  return (
    <div className='w-full h-[calc(100vh-10rem)] flex text-white'>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex-grow bg-[#121212] '>
        <div className='px-8 py-5'>
          {userAlbums ?
            <div>
              <h2 className='text-2xl font-bold pb-5'>Albums</h2>
              <div className='grid grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-5'>
                {userAlbums.map(album => (
                  <UserAlbumCard key={album.id} album={album} />
                  ))}
              </div>
            </div>
            :
            <LoadingAnimation />
          }
        </div>
      </div>
    </div>
  )
}

export default Albums

/* @ts-ignore */
Albums.CustomLayout = CollectionLayout;