import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import PlaylistCard from '../../src/Components/cards/PlaylistCard'
import CollectionLayout from '../../src/Components/layouts/CollectionLayout'
import LoadingAnimation from '../../src/Components/Loading'
import { useAppContext } from '../../src/Config/Context'
import { ContextInterface } from '../../types/types'

const Playlists = () => {
  
  const router = useRouter();
  const { playlists, code } = useAppContext() as ContextInterface;
  console.log(playlists);
  React.useEffect(()=>{
    if(!code) router.replace('/');
  }, [code, router])

  return (
    <div className='w-full h-[calc(100vh-10rem)] flex text-white'>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex-grow bg-[#121212] '>
        <div className='px-8 py-5'>
          {playlists.length > 0 ?
            <div>
              <h2 className='text-2xl font-bold pb-5'>Playlists</h2>
              <div className='grid grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-5'>
                {playlists.map(playlist => (
                  <PlaylistCard key={playlist.id} playlist={playlist} />
                  ))}
              </div>
            </div>
            :
            <LoadingAnimation />
          }
        </div>
      </div>
    </div>
  )
}

export default Playlists

/* @ts-ignore */
Playlists.CustomLayout = CollectionLayout;