import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import ShowCard from '../../src/Components/cards/ShowCard'
import CollectionLayout from '../../src/Components/layouts/CollectionLayout'
import LoadingAnimation from '../../src/Components/Loading'
import { useAppContext } from '../../src/Config/Context'
import { ContextInterface } from '../../types/types'

const Podcasts = () => {
  
  const router = useRouter();
  const { userShows, code } = useAppContext() as ContextInterface;
  React.useEffect(()=>{
    if(!code) router.replace('/');
  }, [code, router])

  return (
    <div className='w-full h-[calc(100vh-10rem)] flex text-white'>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex-grow bg-[#121212] '>
        <div className='px-8 py-5'>
          {userShows && userShows.length > 0 ?
            <div>
              <h2 className='text-2xl font-bold pb-5'>Playlists</h2>
              <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-5'>
                {userShows.map(show => (
                  <ShowCard key={show.id} show={show} />
                ))}
              </div>
            </div>
            :
            <LoadingAnimation />
          }
        </div>
      </div>
    </div>
  )
}

export default Podcasts

/* @ts-ignore */
Podcasts.CustomLayout = CollectionLayout;